Repository rajaskakodkar/tanzu-test-infra, pull requests merged in 2022-03, with the labels that each got.

#1 Seed the test-infra
  OWNERS
  README.md
  config/jobs/build-images/build.yaml
  config/jobs/tanzu-test-infra/postsubmits.yaml
  config/jobs/tanzu-test-infra/presubmits.yaml
  config/jobs/tce/periodics.yaml
  config/prow/boskos/README.md
  config/prow/boskos/boskos-resources.yaml
  config/prow/boskos/cleaner.yaml
  config/prow/boskos/crd.yaml
  config/prow/boskos/janitor.yaml
  config/prow/boskos/kustomization.yaml
  config/prow/boskos/namespace.yaml
  config/prow/boskos/patch-aws-account/job.yaml
  config/prow/boskos/patch-aws-account/rbac.yaml
  config/prow/boskos/rbac.yaml
  config/prow/boskos/reaper.yaml
  config/prow/boskos/resource-configmap.yaml
  config/prow/components.yaml
  config/prow/config.yaml
  config/prow/external-secrets.yaml
  config/prow/kubernetes-external-secrets_crd.yaml
  config/prow/kubernetes-external-secrets_deployment.yaml
  config/prow/kubernetes-external-secrets_rbac.yaml
  config/prow/kubernetes-external-secrets_sa.yaml
  config/prow/kubernetes-external-secrets_service.yaml
  config/prow/plugins.yaml
  config/testgrid/config.yaml
  config/testgrid/default.yaml
  config/testgrid/namespace.yaml
  config/testgrid/summarizer.yaml
  config/testgrid/updater.yaml
  images/dind-go-kubectl/Dockerfile
  images/image-builder/Dockerfile
  images/image-builder/README.md
  images/image-builder/dind.sh
  images/image-builder/entrypoint.sh
  images/image-builder/run.sh
  images/test-image/Dockerfile
  images/test-image/README.md
  images/test-image/boskos.py
  images/test-image/entrypoint.sh
  images/test-image/run.sh
  scripts/ci-docker-build-image.sh
Labels: lgtm

#3 move to prow.tanzu.io
  config/prow/components.yaml
  config/prow/config.yaml
Labels: approved, size/XS

#4 Update OWNERS
  OWNERS
Labels: lgtm, approved, needs-ok-to-test, size/S

#2 Update postsubmits.yaml
  config/jobs/tanzu-test-infra/postsubmits.yaml
Labels: lgtm, approved, size/XS

#5 Update periodics.yaml
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#6 Added job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#7 add triggers for tanzu-test-infra
  config/prow/plugins.yaml
Labels: lgtm, approved, size/S

#8 Update old repo references
  config/jobs/build-images/build.yaml
  config/jobs/tanzu-test-infra/presubmits.yaml
Labels: lgtm, approved, size/XS

#9 Trigger config-update for plugins.yaml
  config/prow/plugins.yaml
Labels: lgtm, approved, size/XS

#10 take 2: Trigger config updater
  config/prow/plugins.yaml
Labels: lgtm, approved, size/XS

#11 Added job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#12 Added dnsPolicy
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#13 Updated the job frequency.
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#14 trigger tce-on-aws job with updates dnsconfig policy
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#15 Update periodics.yaml
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#16 Updated the cronjob
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#17 trigger tce-on-aws
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#18 prob. part fix for failing tce-on-aws job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#19 remove dnspolicy to check for failing tce-on-aws job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#20 Added changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#21 Changed the capd path
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#22 test dnsconfig
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#23 revert dnsconfig changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#24 Minor changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#25 add dns nameservers for cluster.local to tce-on-aws job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#26 fix indentation typo to re-trigger
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#27 add aws us-east-2 dns ns
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#28 remove cluster local ns to test
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#29 Update periodics.yaml
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#30 change dnsPolicy to ClusterFirst from none
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#31 Update periodics.yaml
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved

#32 Testing changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#33 Added changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#34 Added changes
  images/test-image/run.sh
Labels: lgtm, approved, size/XS

#35 Added changes
  config/jobs/tce/periodics.yaml
  images/test-image/run.sh
Labels: lgtm, approved, size/XS

#36 Added changes
  config/jobs/tce/periodics.yaml
  images/test-image/run.sh
Labels: lgtm, approved, size/XS

#37 Added changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#38 Added changes
  config/jobs/tce/periodics.yaml
  images/test-image/run.sh
Labels: lgtm, approved, size/M

#39 Added changes
  config/jobs/tce/periodics.yaml
  images/test-image/run.sh
Labels: lgtm, approved, size/S

#40 Added changes
  images/test-image/run.sh
Labels: lgtm, approved, size/XS

#41 Added changes
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#42 Added changes in test-image
  images/test-image/run.sh
Labels: lgtm, approved, size/S

#43 Added changes
  images/test-image/run.sh
Labels: lgtm, approved, size/XS

#44 Update postsubmit jobs for test-infra
  config/jobs/tanzu-test-infra/postsubmits.yaml
Labels: lgtm, approved, size/XS

#45 Updated run.sh to validate postsubmit jobs
  images/test-image/run.sh
Labels: lgtm, approved, size/XS

#46 Testing the docker periodic job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#47 Updated the new test-image Tag to v20222903-be6db42
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/XS

#48 Removed the testing docker periodic job
  config/jobs/tce/periodics.yaml
Labels: lgtm, approved, size/S

#49 Experimental: migrate to s3 bucket for logs
  config/prow/components.yaml
  config/prow/config.yaml
Labels: lgtm, approved, size/M

#52 Add s3-credentials to deck
  config/prow/components.yaml
Labels: lgtm, approved, size/XS

#53 Replace s3-credentials.json with service-account.json
  config/prow/components.yaml
Labels: lgtm, approved, size/XS

#54 Experimental: Add S3 console URL to gcs_browser_prefix
  config/prow/config.yaml
Labels: lgtm, approved, size/XS

#50 add AndyTauber to OWNERS
  OWNERS
Labels: lgtm, approved, size/XS, ok-to-test

#57 Revert s3 migration
  config/prow/components.yaml
  config/prow/config.yaml
Labels: lgtm, approved, size/M

#58 Update testgrid and job config
  config/jobs/build-images/build.yaml
  config/jobs/tanzu-test-infra/postsubmits.yaml
  config/jobs/tce/periodics.yaml
  config/prow/config.yaml
  config/testgrid/config.yaml
  config/testgrid/default.yaml
Labels: lgtm, approved, size/L
